# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Linton Freund
email: hannahfreund3@gmail.com
author: Linton Freund
description: "Linton's Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/hlfreund 
  - icon: envelope-o
    title: email
    url: mailto:hannahfreund3@gmail.com
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/lintonfreund/
  - icon: file-pdf-o
    title: CV
    url: img/Linton_Freund_CV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
  - icon: twitter
    title: twitter
    url: https://twitter.com/UrFreundLinton
  - icon: fab fa-google
    title: google scholar
    url: https://scholar.google.com/citations?user=yvcDi8gAAAAJ&hl=en&oi=ao
  - icon: fal fa-bacteria
    title: sequencing workflows
    url: https://hlfreund.github.io/workflows.github.io/

